# Generated by Django 6.0.3 on 2026-04-04 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_limit', models.DateTimeField(verbose_name='Date Limit')),
                ('trash', models.BooleanField(verbose_name='Is in trash')),
                ('trash_date_limit', models.DateTimeField(verbose_name='Trash Date Limit')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('assignees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Assignees')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Parent ID')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.priority', verbose_name='Priority')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.progress', verbose_name='Progress')),
                ('team', models.ManyToManyField(to='tasks.team', verbose_name='Team')),
            ],
        ),
    ]
