# Generated by Django 6.0.3 on 2026-04-04 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL, verbose_name='Assignees'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_limit',
            field=models.DateTimeField(null=True, verbose_name='Date Limit'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Parent ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(null=True, to='tasks.team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='trash_date_limit',
            field=models.DateTimeField(null=True, verbose_name='Trash Date Limit'),
        ),
    ]
